### ISSUE TITLE
Add this to the official documentation?

### ISSUE THREAD

**Issue by mastercoms** [uesu/mastercomfig-install-guide#1]
I am happy to accept a new guide, or changes to the current one to improve it! You can find it here: https://github.com/mastercomfig/mastercomfig/blob/develop/docs/

**Comment by uesu** [comment]
Yes! I 'd be happy if you add this to the official documentation. You can change it to your liking, and improve it! hopefully this will help people and there will be fewer issues / problems when installing and how to use cfg's = `autoexec, gameoverrides and modules.` If there's more to discuss and need to adjust the guide, please contact!

**Comment by mastercoms** [comment]
Alright, thanks! I will take a look soon and get back to you.

**Comment by mastercoms** [comment]
So I added a note about checking the changelog when updating, and will also include a template ZIP for the user folder, similar to how it is in this repo.

**Comment by uesu** [comment]
I see ... I see! And I saw it on the docs ! ... including a template ZIP for the user folder really helps and it's easier for them. Should that be classified as advance? adding small instructions how to customize user folder; If they want to customize each class = `class.cfg`, they can customize the sensitivity for each class and add a script for that particular class... etc. I've created a guide for that https://github.com/uesu/advanced-guide

Must be short and easy to understand for people who don't know a lot because mostly they don't want to read and just copy things. Now if they know and test things out, the rest should be for them to experiment and try things and that would build them up.
